apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: nginx-ingress
spec:
  rules:
  - host: jonathan
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
